<?php namespace App\Enums;

use BenSampo\Enum\Enum;
use BenSampo\Enum\Contracts\LocalizedEnum;

final class Countries extends Enum
{
    const AT = 'Австрия';
//    const BY = 'Belarus';
//    const BE = 'Belgium';
//    const BG = 'Bulgaria';
    const CN = 'Китай';
//    const HR = 'Croatia';
//    const CZ = 'Czech Republic';
//    const DK = 'Denmark';
//    const EE = 'Estonia';
//    const FI = 'Finland';
    const FR = 'Франция';
    const DE = 'Германия';
//    const GR = 'Greece';
//    const HK = 'Hong Kong';
    const HU = 'Венгрия';
//    const IN = 'India';
//    const IE = 'Ireland';
    const IT = 'Италия';
    const JP = 'Япония';
//    const KZ = 'Kazakhstan';
    const KP = 'Северная корея';
    const KR = 'Южная Корея';
//    const KG = 'Kyrgyzstan';
//    const LV = 'Latvia';
//    const LI = 'Liechtenstein';
//    const LT = 'Lithuania';
//    const LU = 'Luxembourg';
//    const MK = 'Macedonia, the Former Yugoslav Republic of';
//    const MD = 'Moldova, Republic of';
//    const MC = 'Monaco';
//    const MN = 'Mongolia';
//    const NL = 'Netherlands';
//    const NO = 'Norway';
    const PL = 'Польша';
//    const PT = 'Portugal';
    const RO = 'Румыния';
    const RU = 'Россия';
//    const CS = 'Serbia and Montenegro';
//    const SG = 'Singapore';
//    const SK = 'Slovakia';
//    const SI = 'Slovenia';
//    const ES = 'Spain';
//    const LK = 'Sri Lanka';
//    const SE = 'Sweden';
//    const CH = 'Switzerland';
    const TH = 'Таиланд';
    const TR = 'Турция';
//    const UA = 'Ukraine';
//    const AE = 'United Arab Emirates';
//    const GB = 'United Kingdom';
    const US = 'США';
//    const VN = 'Viet Nam';
}
